apiVersion: apps/v1
kind: Deployment
metadata:
  name: sherlock
  labels:
    app: sherlock
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sherlock
  template:
    metadata:
      labels:
        name: sherlock
    spec:
      automountServiceAccountToken: false
      containers:
        - name: sherlock
          imagePullPolicy: "Always"
          # Use images field in a Kustomization to regularly set/update image tag
          image: "lsstsqre/sherlock-frontend"
          ports:
            - containerPort: 3000
              name: app
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: environments
              mountPath: "/app/environments.json"
              subPath: "environments.json"
            - name: tmp
              mountPath: "/tmp"
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      volumes:
        - name: environments
          secret:
            secretName: sherlock-vaultsecret
            items:
              - key: environments.json
                path: environments.json
        - name: tmp
          emptyDir: {}
