apiVersion: v1
kind: Service
metadata:
  name: sherlock
  labels:
    app: sherlock
spec:
  ports:
    - name: sherlock-http
      protocol: TCP
      port: 3000
      targetPort: app
  selector:
    name: sherlock
